7.1 处理缺失数据

In [2]:
import pandas as pd
import numpy as np

In [3]:
string_data = pd.Series(['aardvark','artichoke',np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [7]:
from numpy import nan as NA

In [8]:
data = pd.Series([1,NA,3.5,NA,7])

In [9]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4] = NA

In [20]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(how = 'all', axis = 1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.randn(7, 3))
df

0         1         2
0  1.340714 -0.971028  0.423763
1  1.048303 -1.688895 -0.389495
2  0.094442 -0.244252  0.331487
3  0.538664  0.695668  0.971187
4 -2.482411  0.394596  0.298434
5 -0.243493 -0.776314  0.326032
6 -0.010392  1.644592  0.428901

In [24]:
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0  1.340714       NaN       NaN
1  1.048303       NaN       NaN
2  0.094442       NaN  0.331487
3  0.538664       NaN  0.971187
4 -2.482411  0.394596  0.298434
5 -0.243493 -0.776314  0.326032
6 -0.010392  1.644592  0.428901

In [25]:
df.dropna()

0         1         2
4 -2.482411  0.394596  0.298434
5 -0.243493 -0.776314  0.326032
6 -0.010392  1.644592  0.428901

In [34]:
df.dropna(thresh = 2)#再看一下什么意思

0         1         2
2  0.094442       NaN  0.331487
3  0.538664       NaN  0.971187
4 -2.482411  0.394596  0.298434
5 -0.243493 -0.776314  0.326032
6 -0.010392  1.644592  0.428901

填充缺失数据

In [35]:
df.fillna(0)

0         1         2
0  1.340714  0.000000  0.000000
1  1.048303  0.000000  0.000000
2  0.094442  0.000000  0.331487
3  0.538664  0.000000  0.971187
4 -2.482411  0.394596  0.298434
5 -0.243493 -0.776314  0.326032
6 -0.010392  1.644592  0.428901

In [37]:
df.fillna({0:0, 1:0.5, 2:0})

0         1         2
0  1.340714  0.500000  0.000000
1  1.048303  0.500000  0.000000
2  0.094442  0.500000  0.331487
3  0.538664  0.500000  0.971187
4 -2.482411  0.394596  0.298434
5 -0.243493 -0.776314  0.326032
6 -0.010392  1.644592  0.428901

In [38]:
_ = df.fillna(0, inplace = True)

In [39]:
df

0         1         2
0  1.340714  0.000000  0.000000
1  1.048303  0.000000  0.000000
2  0.094442  0.000000  0.331487
3  0.538664  0.000000  0.971187
4 -2.482411  0.394596  0.298434
5 -0.243493 -0.776314  0.326032
6 -0.010392  1.644592  0.428901

In [40]:
df = pd.DataFrame(np.random.randn(6,3))
df

0         1         2
0 -0.647770  2.509656 -1.315663
1  0.285314 -0.104844 -0.476654
2  1.259255  1.202844 -1.338130
3  0.504923  0.884353  0.066384
4 -0.101626  0.260478  0.586284
5  0.725113  1.183705  1.215772

In [41]:
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0 -0.647770  2.509656 -1.315663
1  0.285314 -0.104844 -0.476654
2  1.259255       NaN -1.338130
3  0.504923       NaN  0.066384
4 -0.101626       NaN       NaN
5  0.725113       NaN       NaN

In [42]:
df.fillna(method = 'ffill')

0         1         2
0 -0.647770  2.509656 -1.315663
1  0.285314 -0.104844 -0.476654
2  1.259255 -0.104844 -1.338130
3  0.504923 -0.104844  0.066384
4 -0.101626 -0.104844  0.066384
5  0.725113 -0.104844  0.066384

In [52]:
df.fillna(method = 'ffill', limit = 3)#limit 可以连续填充的最大数量

0         1         2
0 -0.647770  2.509656 -1.315663
1  0.285314 -0.104844 -0.476654
2  1.259255 -0.104844 -1.338130
3  0.504923 -0.104844  0.066384
4 -0.101626 -0.104844  0.066384
5  0.725113       NaN  0.066384

In [49]:
data = pd.Series([1., NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [50]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

数据转换

In [54]:
data = pd.DataFrame({'k1':['one', 'two']*3 + ['two'],
                   'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [55]:
data.duplicated()#duplicated 返回一个布尔型Series，表示各行是否重复

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [56]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [57]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [60]:
data.drop_duplicates(['k2'])#过滤掉k2列的重复行

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [61]:
data.drop_duplicates(['k1'], keep = 'last')

k1  k2  v1
4  one   3   4
6  two   4   6

利用函数或映射进行数据转换

In [81]:
data = pd.DataFrame({'food':['bacon', 'pulled pork', 'bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'], 'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [82]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [83]:
meat_to_animal = {'bacon':'pig', 'pulled pork':'cow', 'pastrami':'cow','honey ham':'pig','nova lox': 'salmon','corned beef':'cow'}

In [84]:
lowercased = data['food'].str.lower()

In [85]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [86]:
data['animal'] = lowercased.map(meat_to_animal)

In [87]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     cow
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [88]:
data['food'].map(lambda x: meat_to_animal[x.lower()])#map的方法需要再研究总结

0       pig
1       cow
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

替换值

In [89]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [90]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [91]:
data.replace([-999,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [92]:
data.replace([-999,-1000], [0, np.nan])

0    1.0
1    0.0
2    2.0
3    0.0
4    NaN
5    3.0
dtype: float64

In [93]:
data.replace({-999: 0 , -1000: np.nan})

0    1.0
1    0.0
2    2.0
3    0.0
4    NaN
5    3.0
dtype: float64

重命名轴索引

In [95]:
data = pd.DataFrame(np.arange(12).reshape(3,4), index = ['Ohio','Colorado','New York'], columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [96]:
transform = lambda x :x[:4].upper()

In [97]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [99]:
data.index = data.index.map(transform)

In [100]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [101]:
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [103]:
data.rename(index = {'OHIO':'INDIANA'}, columns = {'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [104]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [105]:
data.rename(index = {'OHIO':'INDIANA'}, columns = {'one':'five'}, inplace = True)

In [106]:
data

five  two  three  four
INDIANA     0    1      2     3
COLO        4    5      6     7
NEW         8    9     10    11

离散化和面元划分

In [108]:
ages = [20,22,25,27,21,24,37,31,61,45,41,32]

In [109]:
bins = [18,25,35,60,100]

In [110]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [112]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [113]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [114]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [120]:
pd.value_counts(pd.cut(ages, [18,25,35,60,100], right = False))

[25, 35)     4
[18, 25)     4
[35, 60)     3
[60, 100)    1
dtype: int64

In [121]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged','Senior']

In [123]:
pd.cut(ages, bins, labels = group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [124]:
data = np.random.randn(20)
data

array([-0.43154254,  2.65384619, -1.62370845,  0.79106182,  0.26990325,
       -1.45110476,  2.57168282, -0.39402558, -0.34548705, -1.29776529,
        0.44064099,  0.10320733, -1.4221464 ,  0.29423661,  0.62668448,
       -2.23339539,  0.48305249, -0.69371885, -1.74445408,  0.68427651])

In [126]:
pd.value_counts(pd.cut(data, 4, precision = 2))

(0.21, 1.43]      7
(-2.24, -1.01]    6
(-1.01, 0.21]     5
(1.43, 2.65]      2
dtype: int64

In [127]:
data = np.random.randn(1000)
data

array([ 7.70826962e-01, -1.52886025e+00, -3.43023423e-01, -1.80751781e-01,
        6.63508218e-01,  3.39444631e-01,  1.22363116e+00, -8.23102300e-01,
        2.97139045e-01,  2.98915700e+00, -2.09891390e-01, -6.32522876e-01,
       -1.64516551e-01, -6.59400493e-02,  1.23943863e+00, -9.33421539e-01,
        5.73659463e-01, -4.61950094e-01, -7.41647542e-01,  1.09952340e+00,
       -7.53530243e-01,  1.51512264e-01,  1.25554732e-02,  3.88686082e-01,
       -3.50956040e-01,  1.10893868e+00, -7.41541723e-01,  8.81599272e-01,
        6.76274575e-02,  4.07479115e-01,  2.20967292e-01,  9.28580739e-01,
       -7.54211394e-01,  1.57374552e+00,  1.61641113e+00,  1.15832165e+00,
        9.44059145e-02, -4.48605494e-02, -3.93996048e-01,  4.44936355e-01,
        3.40610860e-01,  3.50105118e+00,  6.64661868e-02, -2.46346511e+00,
        1.43363238e-01, -1.85801642e+00,  2.91965762e-01,  1.46265922e+00,
       -6.51256379e-01,  4.76599064e-01, -1.14298205e+00,  1.42907490e-01,
       -5.49919509e-02, -

In [128]:
cats = pd.qcut(data, 4)
cats

[(0.725, 3.501], (-3.7239999999999998, -0.656], (-0.656, 0.0464], (-0.656, 0.0464], (0.0464, 0.725], ..., (0.0464, 0.725], (-3.7239999999999998, -0.656], (0.725, 3.501], (0.0464, 0.725], (-0.656, 0.0464]]
Length: 1000
Categories (4, interval[float64]): [(-3.7239999999999998, -0.656] < (-0.656, 0.0464] < (0.0464, 0.725] < (0.725, 3.501]]

In [129]:
pd.value_counts(cats)

(0.725, 3.501]                   250
(0.0464, 0.725]                  250
(-0.656, 0.0464]                 250
(-3.7239999999999998, -0.656]    250
dtype: int64

In [131]:
pd.value_counts(pd.qcut(data, [0,0.1,0.5,0.9,1.]))

(0.0464, 1.279]                  400
(-1.225, 0.0464]                 400
(1.279, 3.501]                   100
(-3.7239999999999998, -1.225]    100
dtype: int64

检测和过滤异常值


In [132]:
data = pd.DataFrame(np.random.randn(1000,4))

In [133]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.024962     0.012394     0.046132     0.008041
std       1.020664     0.986588     0.961863     0.949359
min      -3.012871    -3.180287    -3.199578    -3.095061
25%      -0.692735    -0.633823    -0.613701    -0.617661
50%       0.024816     0.001936     0.053748    -0.010888
75%       0.706545     0.660018     0.691076     0.646555
max       3.200118     2.934561     2.860127     2.969272

In [140]:
col = data[2]

In [143]:
col[np.abs(col) >3]

682   -3.199578
Name: 2, dtype: float64

In [149]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
80   3.200118  1.018130 -0.474624  0.482255
119 -3.012871 -1.369545 -0.995785  0.923714
232  0.113410 -0.208054  0.860085 -3.088756
682 -0.932894 -1.317667 -3.199578  2.558129
903 -1.753204  0.032253  0.956935 -3.095061
915 -0.812552 -3.180287 -1.182845 -1.486231

In [150]:
data[np.abs(data)>3] = np.sign(data)*3

In [152]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.024774     0.012574     0.046332     0.008225
std       1.020022     0.986020     0.961209     0.948767
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.692735    -0.633823    -0.613701    -0.617661
50%       0.024816     0.001936     0.053748    -0.010888
75%       0.706545     0.660018     0.691076     0.646555
max       3.000000     2.934561     2.860127     2.969272

In [154]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0 -1.0 -1.0
2 -1.0 -1.0  1.0 -1.0
3  1.0  1.0  1.0 -1.0
4  1.0  1.0  1.0 -1.0

排列和随机采样

In [155]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [156]:
sampler = np.random.permutation(5)

In [157]:
sampler

array([0, 3, 1, 4, 2])

In [159]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11

In [160]:
df.sample(n = 3)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15

In [161]:
choices = pd.Series([5,7,-1,6,4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [162]:
draws = choices.sample(n =10, replace = True)

In [163]:
draws

3    6
2   -1
0    5
1    7
2   -1
3    6
3    6
4    4
0    5
3    6
dtype: int64

计算指标/哑变量

In [164]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'], 'data1':range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [165]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [166]:
dummies = pd.get_dummies(df['key'], prefix = 'key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [168]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [169]:
mnames = ['movie_id', 'title', 'genres']

In [178]:
movies = pd.read_table('movies.dat', sep='::', header=None, names=mnames)

D:\Users\T470\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [182]:
movies.head(10)

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [186]:
all_genres = []
for i in movies.genres:
    all_genres.extend(i.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [187]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [188]:
dummies = pd.DataFrame(zero_matrix, columns = genres)

In [189]:
gen = movies.genres[0]

In [190]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [191]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [193]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [194]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [195]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [196]:
np.random.seed(12345)

In [197]:
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [198]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [199]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

字符串操作

In [200]:
val = 'a,b,guido'
val

'a,b,guido'

In [202]:
val.split(',')

['a', 'b', 'guido']

In [203]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [204]:
first, second, third = pieces

In [205]:
first + '::' + second + '::' + third

'a::b::guido'

In [207]:
'|'.join(pieces)

'a|b|guido'

In [208]:
'guido' in val

True

In [213]:
val.index(',')

1

In [217]:
val.find(':')#-1代表异常

-1

In [218]:
val.index(':')

ValueError: substring not found

In [220]:
val.count(',')

2

In [221]:
val.replace(',','')

'abguido'

正则表达式

In [223]:
import re

In [225]:
text = 'foo bar\t baz \tqux'
text

'foo bar\t baz \tqux'

In [226]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [228]:
regex = re.compile('\s+')

In [229]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [230]:
regex.findall(text)

[' ', '\t ', ' \t']

pandas的矢量化字符串函数

In [231]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [232]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [233]:
data = pd.Series(data)

In [234]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [235]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [236]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [240]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [241]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [242]:
data.str.findall(pattern, flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [243]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [244]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [245]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [246]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [247]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object